conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('', include("products.urls")),
    path('users/', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'
urlpatterns = [
    path('products/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('products/new/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/edit/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),

    path('reports/', ReportListView.as_view(), name='report_list'),
    path('reports/<int:pk>/', ReportDetailView.as_view(), name='report_detail'),
    path('reports/new/', ReportCreateView.as_view(), name='report_create'),
    path('reports/<int:pk>/edit/', ReportUpdateView.as_view(), name='report_update'),
    path('reports/<int:pk>/delete/', ReportDeleteView.as_view(), name='report_delete'),

    path('products/<int:product_id>/toggle_heart/', toggle_heart, name='toggle_heart'),
    path('products/<int:product_id>/comment/', add_comment, name='add_comment'),

    path('comments/<int:pk>/update/', CommentUpdateView.as_view(), name='comment_update'),
    path('comments/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),

    path('tags/', TagListView.as_view(), name='tag_list'),
]

products/models.py
from django.db import models
from users.models import User


class Product(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    starting_price = models.PositiveIntegerField()
    current_price = models.PositiveIntegerField()
    image = models.ImageField(upload_to='products/', blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # foreign key
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products')
    participants = models.ManyToManyField(User, through='Participants', related_name='participated_products', related_query_name='participated_product')
    tags = models.ManyToManyField('Tag', related_name='products', blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.current_price = self.starting_price
        super().save(*args, **kwargs)

    def participate_in_auction(self, price, user):
        if price is not None and price > self.current_price:
            self.current_price = price
            participant, created = Participants.objects.get_or_create(user=user, product=self,
                                                                      defaults={'current_price': price})
            if not created:
                participant.current_price = price
                participant.save()
            self.save()
            return True
        else:
            return False

class Tag(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # foreign key
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return f"Comment by {self.user.username} on {self.product.title}"


class Heart(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    # foreign key
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='hearts')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='hearts')

    def __str__(self):
        return f'사용자: {self.user}, 상품: {self.product}'


class Report(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    image = models.ImageField(upload_to='products/', blank=True)
    admin_check = models.BooleanField(default=False)
    admin_response = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # foreign key
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reports')

    def __str__(self):
        return self.title


class Participants(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='participated_in_products')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='participants_records')
    current_price = models.PositiveIntegerField()

    def __str__(self):
        return f"User: {self.user}, Product: {self.product}, Current Price: {self.current_price}"

products/forms.py
from django import forms
from .models import Product, Report, Comment, Tag


class ProductForm(forms.ModelForm):
    tags = forms.CharField(label='Tags', max_length=100)

    class Meta:
        model = Product
        fields = ['title', 'content', 'starting_price', 'image']

    def save(self, commit=True):
        instance = super().save(commit=True)  # change commit to True here
        tags = self.cleaned_data.get('tags')
        if tags:
            tags = [tag.strip() for tag in tags.split(',')]
            for tag in tags:
                tag_obj, created = Tag.objects.get_or_create(name=tag)
                instance.tags.add(tag_obj)
        if not commit:
            instance.save()
        return instance


class ProductUpdateForm(forms.ModelForm):
    tags = forms.CharField(label='Tags', max_length=100, required=False)

    class Meta:
        model = Product
        fields = ['title', 'content', 'image', 'status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tags'].initial = ', '.join(tag.name for tag in self.instance.tags.all())

    def save(self, commit=True):
        instance = super().save(commit=True)
        tags = self.cleaned_data.get('tags')
        instance.tags.clear()
        if tags:
            tags = [tag.strip() for tag in tags.split(',')]
            for tag in tags:
                tag_obj, created = Tag.objects.get_or_create(name=tag)
                instance.tags.add(tag_obj)
        if not commit:
            instance.save()
        return instance


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['title', 'content', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']

products/views.py
from django.db.models import Max
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views import View
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .models import Product, Tag, Comment, Heart, Report
from .forms import ProductForm, ProductUpdateForm, ReportForm, CommentForm, TagForm
from django.http import Http404
from django.contrib import messages


def index(request):
    return render(request, 'index.html')


class ProductListView(ListView):
    model = Product
    template_name = 'products/product_list.html'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_likes_this'] = self.object.hearts.filter(user=self.request.user).exists()
        context['liked_users'] = self.object.hearts.all()
        context['comment_form'] = CommentForm()

        product = self.object
        participants_records = product.participants_records.all().order_by('-current_price')
        participants = [(record.user.username, record.current_price) for record in participants_records]
        context['participants'] = participants
        return context

    def post(self, request, *args, **kwargs):
        product = self.get_object()
        price = int(request.POST.get('price', 0))
        if product.participate_in_auction(price, request.user):
            messages.success(request, '경매에 참여하였습니다.')
        else:
            messages.error(request, '현재 가격 이상의 가격을 입력해주세요.')
        return redirect('products:product_detail', pk=product.id)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_form.html'
    success_url = reverse_lazy('products:product_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag_form'] = TagForm()
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.instance.user = self.request.user
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            return JsonResponse(form.errors, status=400)
        else:
            return response


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductUpdateForm
    template_name = 'products/product_form.html'
    success_url = reverse_lazy('products:product_list')

    def test_func(self):
        product = self.get_object()
        if self.request.user == product.user:
            return True
        else:
            return False

    def handle_no_permission(self):
        raise Http404()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['tag_form'] = TagForm(self.request.POST)
        else:
            context['tag_form'] = TagForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super().form_valid(form)
        self.object.tags.clear()
        tags = form.cleaned_data.get('tags').split(',')
        for tag in tags:
            tag = tag.strip()
            if tag:
                obj, created = Tag.objects.get_or_create(name=tag)
                self.object.tags.add(obj)
        return response


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    template_name = 'products/product_confirm_delete.html'
    success_url = reverse_lazy('products:product_list')
    context_object_name = 'product'

    def test_func(self):
        product = self.get_object()
        if self.request.user == product.user:
            return True
        else:
            return False

    def handle_no_permission(self):
        raise Http404()


class ReportListView(ListView):
    model = Report
    template_name = 'products/report_list.html'
    context_object_name = 'report_list'


class ReportDetailView(DetailView):
    model = Report
    template_name = 'products/report_detail.html'
    context_object_name = 'report'


class ReportCreateView(LoginRequiredMixin, CreateView):
    model = Report
    form_class = ReportForm
    template_name = 'products/report_form.html'
    success_url = reverse_lazy('products:report_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ReportUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Report
    form_class = ReportForm
    template_name = 'products/report_form.html'
    success_url = reverse_lazy('products:report_list')

    def test_func(self):
        report = self.get_object()
        if self.request.user == report.user:
            return True
        return False

    def handle_no_permission(self):
        raise Http404()


class ReportDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Report
    template_name = 'products/report_confirm_delete.html'
    success_url = reverse_lazy('products:report_list')
    context_object_name = 'report'

    def test_func(self):
        report = self.get_object()
        if self.request.user == report.user:
            return True
        return False

    def handle_no_permission(self):
        raise Http404()


def toggle_heart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('products:product_detail', args=(product.id,)))

    heart, created = Heart.objects.get_or_create(user=request.user, product=product)
    if not created:
        heart.delete()

    return HttpResponseRedirect(reverse('products:product_detail', args=(product.id,)))


def add_comment(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.product = product
            comment.save()
    return redirect('products:product_detail', pk=product.pk)


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'products/comment_form.html'
    context_object_name = 'comment'

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.user:
            return True
        return False

    def get_success_url(self):
        return reverse('products:product_detail', args=[self.object.product.id])


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'products/comment_confirm_delete.html'
    context_object_name = 'comment'

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.user:
            return True
        return False

    def get_success_url(self):
        return reverse('products:product_detail', args=[self.object.product.id])


class TagListView(ListView):
    model = Tag
    template_name = 'products/tag_list.html'
    context_object_name = 'tag_list'

templates/products/comment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Comment</h1>
  <p>Are you sure you want to delete this comment?</p>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>
{% endblock %}

templates/products/comment_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>Update Comment</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
{% endblock %}

templates/products/product_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Product</h1>
  <p>Are you sure you want to delete "{{ product.name }}"?</p>

  <form method="post">
  {% csrf_token %}
    <input type="submit" value="Confirm">
  </form>
{% endblock %}

templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Title: {{ product.title }}</h1>
  <p>Content: {{ product.content }}</p>
  <p>Username: {{ product.user.username }}</p>
  <p>Starting Price: {{ product.starting_price }}</p>
  <p>Current Price: {{ product.current_price }}</p>
  {% if product.status %}
    <p>Status: 판매중</p>
  {% else %}
    <p>Status: 판매종료</p>
  {% endif %}
  <p>Created: {{ product.created_at }}</p>
  <p>Updated: {{ product.updated_at }}</p>
  {% for tag in product.tags.all %}
    <p>tag: {{ tag }}</p>
  {% endfor %}
  {% for participants in product.participants.all %}
    <p>tag: {{ participants }}</p>
  {% endfor %}
  {% if product.image %}
    <img src="{{ product.image.url }}" alt="Product Image">
  {% endif %}


    <br><br>
{% if request.user.is_authenticated %}
  <form method="post" action="{% url 'products:toggle_heart' product.id %}">
    {% csrf_token %}
    <input type="submit" value="{% if user_likes_this %}Remove Heart{% else %}Add Heart{% endif %}">
  </form>
{% endif %}

<h3>Liked by:</h3>
<ul>
  {% for liked_user in liked_users %}
    <li>{{ liked_user.user.username }}</li>
  {% endfor %}
</ul>

<h3>Comments:</h3>
  <ul>
    {% for comment in product.comments.all %}
      <li>{{ comment.content }} (by {{ comment.user.username }})
        {% if request.user == comment.user %}
          <a href="{% url 'products:comment_update' comment.id %}">Edit</a>
          <a href="{% url 'products:comment_delete' comment.id %}">Delete</a>
        {% endif %}
      </li>
    {% empty %}
      <li>No comments yet.</li>
    {% endfor %}
  </ul>

{% if user.is_authenticated %}
  <form method="post" action="{% url 'products:add_comment' product.id %}">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button type="submit">Add Comment</button>
  </form>
{% else %}
  <p>Please login to add comments.</p>
{% endif %}

  <br><br>
  {% if request.user == product.user %}
    <a href="{% url 'products:product_update' product.id %}">Edit</a>
    <a href="{% url 'products:product_delete' product.id %}">Delete</a>
  {% endif %}

    {%  if not request.user == product.user %}
        <form method="post" action="{% url 'products:product_detail' product.pk %}">
        {% csrf_token %}
        <input type="number" name="price" placeholder="입찰 가격" required>
        <button type="submit">경매 참여</button>
        </form>
    {% endif %}

<h3>Participated Users:</h3>
<ul>
  {% for participant, price in participants %}
    <li>{% if participant == participants.0.0 %}<strong>{{ participant }}</strong> ({{ price }}){% else %}{{ participant }} ({{ price }}){% endif %}</li>
  {% empty %}
    <li>No participants yet.</li>
  {% endfor %}
</ul>


{% endblock %}

templates/products/product_form.html
{% extends 'base.html' %}

{% block content %}
  <h2>New Product</h2>
  <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/products/product_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Product List</h1>

  {% if user.is_authenticated %}
  <a href="{% url 'products:product_create' %}">New Product</a>
  {% endif %}

  {% for product in product_list %}
    <div>
      <h2><a href="{% url 'products:product_detail' product.id %}">{{ product.title }}</a></h2>
    </div>
  {% endfor %}
{% endblock %}

templates/products/report_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Report</h1>
  <p>Are you sure you want to delete the report "{{ report.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Confirm">
  </form>
{% endblock %}

templates/products/report_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ report.title }}</h1>
  <p>{{ report.content }}</p>
  {% if report.image %}
    <img src="{{ report.image.url }}" alt="Report Image">
  {% endif %}
  <p>Created: {{ report.created_at }}</p>
  <p>Updated: {{ report.updated_at }}</p>
  <p>Submitted by: {{ report.user.username }}</p>

  <a href="{% url 'products:report_update' report.id %}">Edit</a>
  <a href="{% url 'products:report_delete' report.id %}">Delete</a>
{% endblock %}

templates/products/report_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>New Report</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/products/report_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Report List</h1>

  {% if user.is_authenticated %}
  <a href="{% url 'products:report_create' %}">고객 신고 등록</a>
  {% endif %}

  {% for report in report_list %}
    <h2><a href="{% url 'products:report_detail' report.id %}">{{ report.title }}</a></h2>
  {% endfor %}
{% endblock %}

templates/products/tag_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Tag List</h2>
  <ul>
    {% for tag in tag_list %}
      <li>{{ tag.name }}</li>
    {% empty %}
      <li>No tags available.</li>
    {% endfor %}
  </ul>
{% endblock %}