conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('', include("products.urls")),
    path('users/', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import *

app_name = 'products'
urlpatterns = [
    path('products/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('products/new/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/edit/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),

    path('reports/', ReportListView.as_view(), name='report_list'),
    path('reports/<int:pk>/', ReportDetailView.as_view(), name='report_detail'),
    path('reports/new/', ReportCreateView.as_view(), name='report_create'),
    path('reports/<int:pk>/edit/', ReportUpdateView.as_view(), name='report_update'),
    path('reports/<int:pk>/delete/', ReportDeleteView.as_view(), name='report_delete'),

    path('products/<int:product_id>/toggle_heart/', toggle_heart, name='toggle_heart'),
    path('products/<int:product_id>/comment/', add_comment, name='add_comment'),

    path('comments/<int:pk>/update/', CommentUpdateView.as_view(), name='comment_update'),
    path('comments/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),

    path('tags/', TagListView.as_view(), name='tag_list'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.user_update, name='user_update'),
    path('profile/delete/', views.user_delete, name='user_delete'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <title>GavelGen</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">GavelGen</a>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
          {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
              </li>
          {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
              </li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-5 text-center">
{% if user.is_authenticated %}
    <h1>{{ user.username }}님, 안녕하세요:)</h1></br>
    <h2><a href="{% url 'users:profile' %}">회원 정보 조회</a></h2>
    <h2><a href="{% url 'products:product_list' %}">상품 조회</a></h2>
    <h2><a href="{% url 'products:report_list' %}">고객 신고 조회</a></h2>
    <br><h2>My Hearts</h2>
  {% for heart in user.hearts.all %}
    <h3><a href="{% url 'products:product_detail' heart.product.id %}">{{ heart.product.title }}</a></h3>
  {% endfor %}
{% else %}
  <h1 class="display-4 font-weight-bold">GavelGen에 오신 것을 환영합니다!</h1>
  <p class="lead">저희 서비스는 경매를 통해 다양한 상품을 구매하고 판매할 수 있는 플랫폼을 제공합니다.</p>
  <p class="lead">로그인 없이 저희가 제공하는 상품들을 둘러볼 수 있으며, 회원 가입과 로그인을 통해 경매에 참여할 수 있습니다.</p>
  <p class="lead">상품을 탐색해보고 싶으시다면, <a href="/products">상품 목록</a>을 확인해보세요.</p>
</div>
{% endif %}

{% endblock %}