conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('', include("products.urls")),
    path('users/', include('users.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.user_update, name='user_update'),
    path('profile/delete/', views.user_delete, name='user_delete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

users/forms.py
from django import forms
from .models import User


class UsernameChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib import messages
from .forms import UsernameChangeForm


def signup(request):  # 회원 가입
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'users/signup.html', {'form': form})


def login(request):    # 로그인
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('index')
        else:
            messages.error(request, 'Invalid username or password.')
    return render(request, 'users/login.html')


@login_required
def logout(request):    # 로그아웃
    auth_logout(request)
    return redirect('index')


@login_required
def profile(request):   # 프로필
    return render(request, 'users/profile.html')


@login_required
def user_update(request):   # 회원 정보 수정
    if request.method == 'POST':
        form = UsernameChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
    else:
        form = UsernameChangeForm(instance=request.user)
    return render(request, 'users/update_profile.html', {'form': form})


@login_required
def user_delete(request):   # 회원 탈퇴
    if request.method == 'POST':
        request.user.delete()
        return redirect('index')
    return render(request, 'users/delete_account.html')

templates/users/delete_account.html
{% extends 'base.html' %}

{% block content %}
  <h2>Delete Account</h2>
  <form method="post">
  {% csrf_token %}
    <p>Are you sure you want to delete your account?</p>
    <button type="submit">Yes, delete my account</button>
  </form>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>login</h2>
  <form method="post">
  {% csrf_token %}
    <p>
      <label for="id_username">Username:</label><br>
      <input type="text" id="id_username" name="username">
    </p>
    <p>
      <label for="id_password">Password:</label><br>
      <input type="password" id="id_password" name="password">
    </p>
    <button type="submit">login</button>
  </form>

  <a class="nav-link" href="{% url 'users:signup' %}">sign up</a>

{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
  <h2>Profile</h2>
  <p>Username: {{ user.username }}</p>
  <a href="{% url 'users:user_update' %}">Update Profile</a>
  <a href="{% url 'users:user_delete' %}">Delete Account</a>
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
  {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/users/update_profile.html
{% extends 'base.html' %}

{% block content %}
  <h2>Update Profile</h2>
  <form method="post">
  {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>
{% endblock %}